spring:
  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

---
spring:
  config:
    activate:
      on-profile: postgres

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/appworks_support_portal}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

app:
  alerts:
    email-enabled: false
    from-address: ${ALERT_FROM_ADDRESS:noreply@example.com}